# Generated by Django 4.2.7 on 2024-01-05 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='borrower',
            field=models.ManyToManyField(blank=True, related_name='purchased', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='category_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorys.category'),
        ),
    ]
