# Generated by Django 4.2.7 on 2024-01-05 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_booksmodel_borrower_booksmodel_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='user_reviews',
            field=models.ManyToManyField(blank=True, related_name='book_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
