# Generated by Django 4.2.7 on 2024-01-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='borrow',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
