# Generated by Django 4.2.7 on 2024-01-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
    ]
